"""The numbers quoted in the preprint's ablation paragraph -> LaTeX macros.

    python ablation_numbers.py

Reads `results/ablation/`, writes `figures/ablation_numbers.tex`: one
`\\newcommand` per number the prose quotes, so the text is mechanically bound
to the extracted data instead of hand-transcribed. Units and math wrapping
stay in the prose; a macro expands to the bare (math-mode) number.

Also asserts the paragraph's structural claims -- every $|\\delta C_V| > 1\\%$
tail coincides with a change in the dropped-mode count, with exactly one
exception -- so a change in the data breaks this fragment loudly instead of
silently invalidating the text.
"""

import argparse
import math
from statistics import median

import ablation_load

from sadmof.tbx import savefile

TEMPERATURE = "300"
# The prose's scope: the table's five ablations plus the `precision`
# composite; `precision_bare` is a diagnostic outside the narrative.
ABLATIONS = ("precision_fp32", "precision_tf32", "precision", "d3", "shadow", "production")


def main():
    build_parser().parse_args()
    stats = gather()
    check_tail_claims()

    models = ("mace", "pet-xs", "pet-s")
    macros = (
        # -- fp32-proper rung: the ceiling over the three per-model medians
        (
            "ablFpMedCeil",
            sci_ceil(max(stats[(m, "precision_fp32")]["med"] for m in models)),
        ),
        # -- production composite: worst per-model median and overall worst case
        ("ablProdMedHi", f"{max(stats[(m, 'production')]['med'] for m in models):.2f}"),
        ("ablProdMax", f"{max(stats[(m, 'production')]['max'] for m in models):.1f}"),
        # -- the one genuine (non-threshold) tail
        ("ablDispStruct", exception_pair()["structure"]),
        ("ablDispShift", f"{exception_pair()['dnu_max_cm1_asr']:.0f}"),
        ("ablDispShiftCv", f"{abs(ablation_load.dcv_pct(exception_pair())):.1f}"),
    )

    lines = ["% generated by work/hessian-ablations/ablation_numbers.py -- do not edit"]
    for name, value in macros:
        lines.append(rf"\newcommand{{\{name}}}{{{value}}}")
        print(f"\\{name:16s} {value}")
    savefile("\n".join(lines) + "\n", "figures/ablation_numbers.tex")


# ---------------------------------------------------------------------------
# Statistics and claims
# ---------------------------------------------------------------------------


def gather():
    """`{(model, ablation): {med, max}}`, |dCv| in percent at 300 K, ASR."""
    stats = {}
    for (model, ablation), rows in ablation_load.by_ablation().items():
        dcv = [abs(ablation_load.dcv_pct(r, TEMPERATURE)) for r in rows]
        stats[(model, ablation)] = {"med": median(dcv), "max": max(dcv)}
    return stats


def tail_pairs():
    """Every pair in the prose's scope with |dCv(300 K, ASR)| > 1 %, and whether
    its dropped-mode count changed between the two conditions."""
    out = []
    for structure in ablation_load.available():
        meta = ablation_load.load(structure)
        for pair in meta["pairs"]:
            if pair["ablation"] not in ABLATIONS:
                continue
            dcv = ablation_load.dcv_pct(pair)
            if dcv is None or abs(dcv) <= 1.0:
                continue
            flip = (
                meta["conditions"][pair["ablated"]]["n_dropped_asr"]
                != meta["conditions"][pair["reference"]]["n_dropped_asr"]
            )
            out.append({"structure": structure, "flip": flip, **pair})
    return out


def check_tail_claims():
    """The block-4 claims: all >1 % tails are dropped-mode flips, except one.

    The one genuine spectral shift is RSM0274/mace losing D3; with the
    production composite anchored on the mmhigh corner (no TF32 mode churn),
    the same D3 shift shows through the composite for that structure too —
    one cause, visible in two rows.
    """
    exceptions = [
        (p["structure"], p["family"], p["ablation"]) for p in tail_pairs() if not p["flip"]
    ]
    assert exceptions == [
        ("RSM0274", "mace", "d3"),
        ("RSM0274", "mace", "production"),
    ], exceptions


def exception_pair():
    """The single genuine tail: D3 on RSM0274, no mode-count change.

    The production composite inherits the same shift (see check_tail_claims);
    the quoted exception is the isolated D3 pair.
    """
    (pair,) = [p for p in tail_pairs() if not p["flip"] and p["ablation"] == "d3"]
    return pair


# ---------------------------------------------------------------------------
# Formatting
# ---------------------------------------------------------------------------


def sci_ceil(x):
    """One-significant-figure scientific upper bound as bare math: 5\\times10^{-5}."""
    exponent = math.floor(math.log10(abs(x)))
    mantissa = math.ceil(x / 10**exponent)
    return rf"{mantissa}\times10^{{{exponent}}}"


def build_parser():
    return argparse.ArgumentParser(description=__doc__)


if __name__ == "__main__":
    main()
